# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/nsarras/Storage Building Blocks/Storage Building Blocks.cache/wt} [current_project]
set_property parent.project_path {C:/Users/nsarras/Storage Building Blocks/Storage Building Blocks.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/nsarras/Storage Building Blocks/Storage Building Blocks.srcs/sources_1/new/FIFO.v}}
read_xdc {{C:/Users/nsarras/Storage Building Blocks/Storage Building Blocks.srcs/constrs_1/new/FPGA.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/nsarras/Storage Building Blocks/Storage Building Blocks.srcs/constrs_1/new/FPGA.xdc}}]

synth_design -top FIFO -part xc7a100tcsg324-1
write_checkpoint -noxdef FIFO.dcp
catch { report_utilization -file FIFO_utilization_synth.rpt -pb FIFO_utilization_synth.pb }
